//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowyImageCopy.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnowyImageCopy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Check に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Check {
            get {
                return ResourceManager.GetString("Command_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check &amp; Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_CheckCopy {
            get {
                return ResourceManager.GetString("Command_CheckCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_CheckCopyAuto {
            get {
                return ResourceManager.GetString("Command_CheckCopyAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Copy {
            get {
                return ResourceManager.GetString("Command_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To Desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Send {
            get {
                return ResourceManager.GetString("Command_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Stop {
            get {
                return ResourceManager.GetString("Command_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CurrentImage {
            get {
                return ResourceManager.GetString("CurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon Feather {
            get {
                object obj = ResourceManager.GetObject("Feather", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Copied に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileStatus_Copied {
            get {
                return ResourceManager.GetString("FileStatus_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copying に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileStatus_Copying {
            get {
                return ResourceManager.GetString("FileStatus_Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Copied に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileStatus_NotCopied {
            get {
                return ResourceManager.GetString("FileStatus_NotCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recycled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileStatus_Recycled {
            get {
                return ResourceManager.GetString("FileStatus_Recycled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To Be Copied に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileStatus_ToBeCopied {
            get {
                return ResourceManager.GetString("FileStatus_ToBeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileStatus_Unknown {
            get {
                return ResourceManager.GetString("FileStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weird に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileStatus_Weird {
            get {
                return ResourceManager.GetString("FileStatus_Weird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_CheckCompleted {
            get {
                return ResourceManager.GetString("OperationStatus_CheckCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking FlashAir. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_Checking {
            get {
                return ResourceManager.GetString("OperationStatus_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_Completed {
            get {
                return ResourceManager.GetString("OperationStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lost connection to FlashAir. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_ConnectionLost {
            get {
                return ResourceManager.GetString("OperationStatus_ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot connect to FlashAir. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_ConnectionUnable {
            get {
                return ResourceManager.GetString("OperationStatus_ConnectionUnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy completed. ({0} images, {1} seconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_CopyCompleted {
            get {
                return ResourceManager.GetString("OperationStatus_CopyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copying from FlashAir. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_Copying {
            get {
                return ResourceManager.GetString("OperationStatus_Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete in FlashAir (upload.cgi) is disabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_DeleteDisabled {
            get {
                return ResourceManager.GetString("OperationStatus_DeleteDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to delete image in FlashAir. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_DeleteFailed {
            get {
                return ResourceManager.GetString("OperationStatus_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error happened. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_Error {
            get {
                return ResourceManager.GetString("OperationStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No date is selected in calendar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_NoDateCalender {
            get {
                return ResourceManager.GetString("OperationStatus_NoDateCalender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No file to be copied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_NoFileToBeCopied {
            get {
                return ResourceManager.GetString("OperationStatus_NoFileToBeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PC is not connected to network. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_NoNetwork {
            get {
                return ResourceManager.GetString("OperationStatus_NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specified folder is not found in FlashAir. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_NotFolderFound {
            get {
                return ResourceManager.GetString("OperationStatus_NotFolderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FlashAir is changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_NotSameFlashAir {
            get {
                return ResourceManager.GetString("OperationStatus_NotSameFlashAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_Stopped {
            get {
                return ResourceManager.GetString("OperationStatus_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection timed out. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_TimedOut {
            get {
                return ResourceManager.GetString("OperationStatus_TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot access local folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("OperationStatus_UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting for auto check time. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationStatus_WaitingAutoCheck {
            get {
                return ResourceManager.GetString("OperationStatus_WaitingAutoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Check に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_AutoCheck {
            get {
                return ResourceManager.GetString("Options_AutoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Check Interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_AutoCheckInterval {
            get {
                return ResourceManager.GetString("Options_AutoCheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_Browse {
            get {
                return ResourceManager.GetString("Options_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable to choose to delete image in FlashAir on copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_ChooseDeleteOnCopy {
            get {
                return ResourceManager.GetString("Options_ChooseDeleteOnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_Date {
            get {
                return ResourceManager.GetString("Options_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_DateAll {
            get {
                return ResourceManager.GetString("Options_DateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select from calendar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_DateSelect {
            get {
                return ResourceManager.GetString("Options_DateSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_DateToday {
            get {
                return ResourceManager.GetString("Options_DateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete On Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_DeleteOnCopy {
            get {
                return ResourceManager.GetString("Options_DeleteOnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make file extension lowercase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_ExtensionLowercase {
            get {
                return ResourceManager.GetString("Options_ExtensionLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_File {
            get {
                return ResourceManager.GetString("Options_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_Info {
            get {
                return ResourceManager.GetString("Options_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Instant Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_InstantCopy {
            get {
                return ResourceManager.GetString("Options_InstantCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_Language {
            get {
                return ResourceManager.GetString("Options_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local Folder (Copy Destination) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_LocalFolder {
            get {
                return ResourceManager.GetString("Options_LocalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify a folder to copy images. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_LocalFolderExplanation {
            get {
                return ResourceManager.GetString("Options_LocalFolderExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open by Explorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_OpenByExplorer {
            get {
                return ResourceManager.GetString("Options_OpenByExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_Path {
            get {
                return ResourceManager.GetString("Options_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to Recycle if image in FlashAir is deleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_Recycle {
            get {
                return ResourceManager.GetString("Options_Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FlashAir Address (Copy Source) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_RemoteAddress {
            get {
                return ResourceManager.GetString("Options_RemoteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select only ReadOnly image on check に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_SelectReadOnly {
            get {
                return ResourceManager.GetString("Options_SelectReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://emoacht.github.io/SnowyImageCopy/index.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProjectSite {
            get {
                return ResourceManager.GetString("ProjectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   readme_en.html#delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReadmeFile {
            get {
                return ResourceManager.GetString("ReadmeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This app will terminate, because unexpected problem happened. Leave exception log on Desktop? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordException {
            get {
                return ResourceManager.GetString("RecordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy from FlashAir completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToastBody_CopyCompleted {
            get {
                return ResourceManager.GetString("ToastBody_CopyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ({0} images, {1} seconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToastBodyExtra_CopyCompleted {
            get {
                return ResourceManager.GetString("ToastBodyExtra_CopyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToastHeadline_CopyCompleted {
            get {
                return ResourceManager.GetString("ToastHeadline_CopyCompleted", resourceCulture);
            }
        }
    }
}
