//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowyImageCopy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnowyImageCopy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address name.
        /// </summary>
        public static string Card_AddressName {
            get {
                return ResourceManager.GetString("Card_AddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Card_Apply {
            get {
                return ResourceManager.GetString("Card_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic timeout (only for Automatic startup and AP mode).
        /// </summary>
        public static string Card_AutomaticTimeout {
            get {
                return ResourceManager.GetString("Card_AutomaticTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Card_Capacity {
            get {
                return ResourceManager.GetString("Card_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        public static string Card_Drive {
            get {
                return ResourceManager.GetString("Card_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        public static string Card_Firmware {
            get {
                return ResourceManager.GetString("Card_Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free space.
        /// </summary>
        public static string Card_FreeSpace {
            get {
                return ResourceManager.GetString("Card_FreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless LAN mode.
        /// </summary>
        public static string Card_LanMode {
            get {
                return ResourceManager.GetString("Card_LanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP (Access Point) mode.
        /// </summary>
        public static string Card_LanModeAP {
            get {
                return ResourceManager.GetString("Card_LanModeAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet pass-thru mode.
        /// </summary>
        public static string Card_LanModeIPT {
            get {
                return ResourceManager.GetString("Card_LanModeIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STA (Station) mode.
        /// </summary>
        public static string Card_LanModeSTA {
            get {
                return ResourceManager.GetString("Card_LanModeSTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless LAN startup.
        /// </summary>
        public static string Card_LanStartup {
            get {
                return ResourceManager.GetString("Card_LanStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic startup.
        /// </summary>
        public static string Card_LanStartupAutomatic {
            get {
                return ResourceManager.GetString("Card_LanStartupAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual startup.
        /// </summary>
        public static string Card_LanStartupManual {
            get {
                return ResourceManager.GetString("Card_LanStartupManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlashAir card (local).
        /// </summary>
        public static string Card_LocalCard {
            get {
                return ResourceManager.GetString("Card_LocalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufactured.
        /// </summary>
        public static string Card_Manufactured {
            get {
                return ResourceManager.GetString("Card_Manufactured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name.
        /// </summary>
        public static string Card_ModelName {
            get {
                return ResourceManager.GetString("Card_ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlashAir card (remote).
        /// </summary>
        public static string Card_RemoteCard {
            get {
                return ResourceManager.GetString("Card_RemoteCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string Card_Revision {
            get {
                return ResourceManager.GetString("Card_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Card_Search {
            get {
                return ResourceManager.GetString("Card_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network security key.
        /// </summary>
        public static string Card_SecurityKey {
            get {
                return ResourceManager.GetString("Card_SecurityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        public static string Card_SerialNumber {
            get {
                return ResourceManager.GetString("Card_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSID.
        /// </summary>
        public static string Card_Ssid {
            get {
                return ResourceManager.GetString("Card_Ssid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access point built into FlashAir (for AP mode, Internet pass-thru mode).
        /// </summary>
        public static string Card_ToBuiltinAP {
            get {
                return ResourceManager.GetString("Card_ToBuiltinAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access point to which FlashAir is to connect (for STA mode, Internet pass-thru mode).
        /// </summary>
        public static string Card_ToRouterAP {
            get {
                return ResourceManager.GetString("Card_ToRouterAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconnected.
        /// </summary>
        public static string Card_Unconnected {
            get {
                return ResourceManager.GetString("Card_Unconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unretrieved.
        /// </summary>
        public static string Card_Unretrieved {
            get {
                return ResourceManager.GetString("Card_Unretrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.cgi.
        /// </summary>
        public static string Card_Upload {
            get {
                return ResourceManager.GetString("Card_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used capacity.
        /// </summary>
        public static string Card_UsedCapacity {
            get {
                return ResourceManager.GetString("Card_UsedCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Command_Check {
            get {
                return ResourceManager.GetString("Command_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check &amp; Copy.
        /// </summary>
        public static string Command_CheckCopy {
            get {
                return ResourceManager.GetString("Command_CheckCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Command_CheckCopyAuto {
            get {
                return ResourceManager.GetString("Command_CheckCopyAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Command_Copy {
            get {
                return ResourceManager.GetString("Command_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Desktop.
        /// </summary>
        public static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Clipboard.
        /// </summary>
        public static string Command_Send {
            get {
                return ResourceManager.GetString("Command_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Command_Stop {
            get {
                return ResourceManager.GetString("Command_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Image.
        /// </summary>
        public static string CurrentImage {
            get {
                return ResourceManager.GetString("CurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Feather {
            get {
                object obj = ResourceManager.GetObject("Feather", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        public static string FileStatus_Copied {
            get {
                return ResourceManager.GetString("FileStatus_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        public static string FileStatus_Copying {
            get {
                return ResourceManager.GetString("FileStatus_Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Copied.
        /// </summary>
        public static string FileStatus_NotCopied {
            get {
                return ResourceManager.GetString("FileStatus_NotCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once Copied.
        /// </summary>
        public static string FileStatus_OnceCopied {
            get {
                return ResourceManager.GetString("FileStatus_OnceCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycled.
        /// </summary>
        public static string FileStatus_Recycled {
            get {
                return ResourceManager.GetString("FileStatus_Recycled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Be Copied.
        /// </summary>
        public static string FileStatus_ToBeCopied {
            get {
                return ResourceManager.GetString("FileStatus_ToBeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string FileStatus_Unknown {
            get {
                return ResourceManager.GetString("FileStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weird.
        /// </summary>
        public static string FileStatus_Weird {
            get {
                return ResourceManager.GetString("FileStatus_Weird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to license.html.
        /// </summary>
        public static string LicenseFile {
            get {
                return ResourceManager.GetString("LicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied new settings to FlashAir in local..
        /// </summary>
        public static string OperationStatus_Card_Applied {
            get {
                return ResourceManager.GetString("OperationStatus_Card_Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying new settings to FlashAir in local..
        /// </summary>
        public static string OperationStatus_Card_Applying {
            get {
                return ResourceManager.GetString("OperationStatus_Card_Applying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No FlashAir in local is found..
        /// </summary>
        public static string OperationStatus_Card_NoFound {
            get {
                return ResourceManager.GetString("OperationStatus_Card_NoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A FlashAir in local is found..
        /// </summary>
        public static string OperationStatus_Card_OneFound {
            get {
                return ResourceManager.GetString("OperationStatus_Card_OneFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A FlashAir in local is replaced..
        /// </summary>
        public static string OperationStatus_Card_Replaced {
            get {
                return ResourceManager.GetString("OperationStatus_Card_Replaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching FlashAir in local..
        /// </summary>
        public static string OperationStatus_Card_Searching {
            get {
                return ResourceManager.GetString("OperationStatus_Card_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check completed..
        /// </summary>
        public static string OperationStatus_CheckCompleted {
            get {
                return ResourceManager.GetString("OperationStatus_CheckCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking FlashAir..
        /// </summary>
        public static string OperationStatus_Checking {
            get {
                return ResourceManager.GetString("OperationStatus_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        public static string OperationStatus_Completed {
            get {
                return ResourceManager.GetString("OperationStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to FlashAir..
        /// </summary>
        public static string OperationStatus_ConnectionLost {
            get {
                return ResourceManager.GetString("OperationStatus_ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to FlashAir..
        /// </summary>
        public static string OperationStatus_ConnectionUnable {
            get {
                return ResourceManager.GetString("OperationStatus_ConnectionUnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy completed. ({0} images, {1} seconds).
        /// </summary>
        public static string OperationStatus_CopyCompleted {
            get {
                return ResourceManager.GetString("OperationStatus_CopyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying from FlashAir..
        /// </summary>
        public static string OperationStatus_Copying {
            get {
                return ResourceManager.GetString("OperationStatus_Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete in FlashAir (upload.cgi) is disabled..
        /// </summary>
        public static string OperationStatus_DeleteDisabled {
            get {
                return ResourceManager.GetString("OperationStatus_DeleteDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete image in FlashAir..
        /// </summary>
        public static string OperationStatus_DeleteFailed {
            get {
                return ResourceManager.GetString("OperationStatus_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened..
        /// </summary>
        public static string OperationStatus_Error {
            get {
                return ResourceManager.GetString("OperationStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed..
        /// </summary>
        public static string OperationStatus_Failed {
            get {
                return ResourceManager.GetString("OperationStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access local file..
        /// </summary>
        public static string OperationStatus_LocalFileAccessUnable {
            get {
                return ResourceManager.GetString("OperationStatus_LocalFileAccessUnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of local folder is wrong..
        /// </summary>
        public static string OperationStatus_LocalFolderInvalid {
            get {
                return ResourceManager.GetString("OperationStatus_LocalFolderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to local folder is denied..
        /// </summary>
        public static string OperationStatus_LocalFolderUnauthorized {
            get {
                return ResourceManager.GetString("OperationStatus_LocalFolderUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No date is selected in calendar..
        /// </summary>
        public static string OperationStatus_NoDateCalender {
            get {
                return ResourceManager.GetString("OperationStatus_NoDateCalender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file to be copied..
        /// </summary>
        public static string OperationStatus_NoFileToBeCopied {
            get {
                return ResourceManager.GetString("OperationStatus_NoFileToBeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC is not connected to network..
        /// </summary>
        public static string OperationStatus_NoNetwork {
            get {
                return ResourceManager.GetString("OperationStatus_NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified folder is not found in FlashAir..
        /// </summary>
        public static string OperationStatus_NotFolderFound {
            get {
                return ResourceManager.GetString("OperationStatus_NotFolderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlashAir is changed..
        /// </summary>
        public static string OperationStatus_NotSameFlashAir {
            get {
                return ResourceManager.GetString("OperationStatus_NotSameFlashAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped..
        /// </summary>
        public static string OperationStatus_Stopped {
            get {
                return ResourceManager.GetString("OperationStatus_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timed out..
        /// </summary>
        public static string OperationStatus_TimedOut {
            get {
                return ResourceManager.GetString("OperationStatus_TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for auto check time..
        /// </summary>
        public static string OperationStatus_WaitingAutoCheck {
            get {
                return ResourceManager.GetString("OperationStatus_WaitingAutoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto at start.
        /// </summary>
        public static string Options_AutoAtStart {
            get {
                return ResourceManager.GetString("Options_AutoAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Check Interval.
        /// </summary>
        public static string Options_AutoCheckInterval {
            get {
                return ResourceManager.GetString("Options_AutoCheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Options_Browse {
            get {
                return ResourceManager.GetString("Options_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose to delete image in FlashAir on copy.
        /// </summary>
        public static string Options_ChooseDeleteOnCopy {
            get {
                return ResourceManager.GetString("Options_ChooseDeleteOnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Options_Connection {
            get {
                return ResourceManager.GetString("Options_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy on select.
        /// </summary>
        public static string Options_CopyOnSelect {
            get {
                return ResourceManager.GetString("Options_CopyOnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder for each date.
        /// </summary>
        public static string Options_CreateDatedFolder {
            get {
                return ResourceManager.GetString("Options_CreateDatedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize folder name for each date.
        /// </summary>
        public static string Options_CustomizeDatedFolder {
            get {
                return ResourceManager.GetString("Options_CustomizeDatedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Options_Date {
            get {
                return ResourceManager.GetString("Options_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Options_DateAll {
            get {
                return ResourceManager.GetString("Options_DateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from calendar.
        /// </summary>
        public static string Options_DateSelect {
            get {
                return ResourceManager.GetString("Options_DateSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Options_DateToday {
            get {
                return ResourceManager.GetString("Options_DateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete image in FlashAir on copy.
        /// </summary>
        public static string Options_DeleteOnCopy {
            get {
                return ResourceManager.GetString("Options_DeleteOnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make file extension lowercase.
        /// </summary>
        public static string Options_ExtensionLowercase {
            get {
                return ResourceManager.GetString("Options_ExtensionLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Options_File {
            get {
                return ResourceManager.GetString("Options_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle JPEG image only.
        /// </summary>
        public static string Options_HandleJpegOnly {
            get {
                return ResourceManager.GetString("Options_HandleJpegOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Options_Info {
            get {
                return ResourceManager.GetString("Options_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Options_Language {
            get {
                return ResourceManager.GetString("Options_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not overwrite existing image.
        /// </summary>
        public static string Options_LeaveExisting {
            get {
                return ResourceManager.GetString("Options_LeaveExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Folder (Copy Destination).
        /// </summary>
        public static string Options_LocalFolder {
            get {
                return ResourceManager.GetString("Options_LocalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select local folder.
        /// </summary>
        public static string Options_LocalFolderTitle {
            get {
                return ResourceManager.GetString("Options_LocalFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not select once copied image on check.
        /// </summary>
        public static string Options_OnceCopied {
            get {
                return ResourceManager.GetString("Options_OnceCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open by Explorer.
        /// </summary>
        public static string Options_OpenByExplorer {
            get {
                return ResourceManager.GetString("Options_OpenByExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order from newer image.
        /// </summary>
        public static string Options_OrderFromNewer {
            get {
                return ResourceManager.GetString("Options_OrderFromNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Options_Path {
            get {
                return ResourceManager.GetString("Options_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Recycle Bin if image in FlashAir is deleted.
        /// </summary>
        public static string Options_Recycle {
            get {
                return ResourceManager.GetString("Options_Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlashAir Address (Copy Source).
        /// </summary>
        public static string Options_RemoteAddress {
            get {
                return ResourceManager.GetString("Options_RemoteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only Read-only image on check.
        /// </summary>
        public static string Options_SelectReadOnly {
            get {
                return ResourceManager.GetString("Options_SelectReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Options_Sound {
            get {
                return ResourceManager.GetString("Options_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All images copied.
        /// </summary>
        public static string Options_SoundAllCopied {
            get {
                return ResourceManager.GetString("Options_SoundAllCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy started.
        /// </summary>
        public static string Options_SoundCopyStarted {
            get {
                return ResourceManager.GetString("Options_SoundCopyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAVE files (*.wav)|*.wav|All files (*.*)|*.*.
        /// </summary>
        public static string Options_SoundFilter {
            get {
                return ResourceManager.GetString("Options_SoundFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An image copied.
        /// </summary>
        public static string Options_SoundOneCopied {
            get {
                return ResourceManager.GetString("Options_SoundOneCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play notification sound.
        /// </summary>
        public static string Options_SoundPlay {
            get {
                return ResourceManager.GetString("Options_SoundPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open WAVE file.
        /// </summary>
        public static string Options_SoundTitle {
            get {
                return ResourceManager.GetString("Options_SoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Options_Test {
            get {
                return ResourceManager.GetString("Options_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout Duration.
        /// </summary>
        public static string Options_TimeoutDuration {
            get {
                return ResourceManager.GetString("Options_TimeoutDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readme.
        /// </summary>
        public static string Readme {
            get {
                return ResourceManager.GetString("Readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to readme_en.html.
        /// </summary>
        public static string ReadmeFile {
            get {
                return ResourceManager.GetString("ReadmeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to readme_en.html#delete.
        /// </summary>
        public static string ReadmeFileDelete {
            get {
                return ResourceManager.GetString("ReadmeFileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app will terminate, because unexpected problem happened. Leave exception log on Desktop?.
        /// </summary>
        public static string RecordException {
            get {
                return ResourceManager.GetString("RecordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/emoacht/SnowyImageCopy.
        /// </summary>
        public static string SiteUrl {
            get {
                return ResourceManager.GetString("SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from FlashAir completed..
        /// </summary>
        public static string ToastBody_CopyCompleted {
            get {
                return ResourceManager.GetString("ToastBody_CopyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} images, {1} seconds).
        /// </summary>
        public static string ToastBodyFormat_CopyCompleted {
            get {
                return ResourceManager.GetString("ToastBodyFormat_CopyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Completed.
        /// </summary>
        public static string ToastTitle_CopyCompleted {
            get {
                return ResourceManager.GetString("ToastTitle_CopyCompleted", resourceCulture);
            }
        }
    }
}
