//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowyImageCopy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnowyImageCopy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Command_Check {
            get {
                return ResourceManager.GetString("Command_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check &amp; Copy.
        /// </summary>
        public static string Command_CheckCopy {
            get {
                return ResourceManager.GetString("Command_CheckCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Command_CheckCopyAuto {
            get {
                return ResourceManager.GetString("Command_CheckCopyAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Command_Copy {
            get {
                return ResourceManager.GetString("Command_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Desktop.
        /// </summary>
        public static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Clipboard.
        /// </summary>
        public static string Command_Send {
            get {
                return ResourceManager.GetString("Command_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Command_Stop {
            get {
                return ResourceManager.GetString("Command_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Image.
        /// </summary>
        public static string CurrentImage {
            get {
                return ResourceManager.GetString("CurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Feather {
            get {
                object obj = ResourceManager.GetObject("Feather", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        public static string FileStatus_Copied {
            get {
                return ResourceManager.GetString("FileStatus_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        public static string FileStatus_Copying {
            get {
                return ResourceManager.GetString("FileStatus_Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Copied.
        /// </summary>
        public static string FileStatus_NotCopied {
            get {
                return ResourceManager.GetString("FileStatus_NotCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once Copied.
        /// </summary>
        public static string FileStatus_OnceCopied {
            get {
                return ResourceManager.GetString("FileStatus_OnceCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycled.
        /// </summary>
        public static string FileStatus_Recycled {
            get {
                return ResourceManager.GetString("FileStatus_Recycled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Be Copied.
        /// </summary>
        public static string FileStatus_ToBeCopied {
            get {
                return ResourceManager.GetString("FileStatus_ToBeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string FileStatus_Unknown {
            get {
                return ResourceManager.GetString("FileStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weird.
        /// </summary>
        public static string FileStatus_Weird {
            get {
                return ResourceManager.GetString("FileStatus_Weird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check completed..
        /// </summary>
        public static string OperationStatus_CheckCompleted {
            get {
                return ResourceManager.GetString("OperationStatus_CheckCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking FlashAir..
        /// </summary>
        public static string OperationStatus_Checking {
            get {
                return ResourceManager.GetString("OperationStatus_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        public static string OperationStatus_Completed {
            get {
                return ResourceManager.GetString("OperationStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to FlashAir..
        /// </summary>
        public static string OperationStatus_ConnectionLost {
            get {
                return ResourceManager.GetString("OperationStatus_ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to FlashAir..
        /// </summary>
        public static string OperationStatus_ConnectionUnable {
            get {
                return ResourceManager.GetString("OperationStatus_ConnectionUnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy completed. ({0} images, {1} seconds).
        /// </summary>
        public static string OperationStatus_CopyCompleted {
            get {
                return ResourceManager.GetString("OperationStatus_CopyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying from FlashAir..
        /// </summary>
        public static string OperationStatus_Copying {
            get {
                return ResourceManager.GetString("OperationStatus_Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete in FlashAir (upload.cgi) is disabled..
        /// </summary>
        public static string OperationStatus_DeleteDisabled {
            get {
                return ResourceManager.GetString("OperationStatus_DeleteDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete image in FlashAir..
        /// </summary>
        public static string OperationStatus_DeleteFailed {
            get {
                return ResourceManager.GetString("OperationStatus_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened..
        /// </summary>
        public static string OperationStatus_Error {
            get {
                return ResourceManager.GetString("OperationStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access local file..
        /// </summary>
        public static string OperationStatus_LocalFileAccessUnable {
            get {
                return ResourceManager.GetString("OperationStatus_LocalFileAccessUnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of local folder is wrong..
        /// </summary>
        public static string OperationStatus_LocalFolderInvalid {
            get {
                return ResourceManager.GetString("OperationStatus_LocalFolderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to local folder is denied..
        /// </summary>
        public static string OperationStatus_LocalFolderUnauthorized {
            get {
                return ResourceManager.GetString("OperationStatus_LocalFolderUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No date is selected in calendar..
        /// </summary>
        public static string OperationStatus_NoDateCalender {
            get {
                return ResourceManager.GetString("OperationStatus_NoDateCalender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file to be copied..
        /// </summary>
        public static string OperationStatus_NoFileToBeCopied {
            get {
                return ResourceManager.GetString("OperationStatus_NoFileToBeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC is not connected to network..
        /// </summary>
        public static string OperationStatus_NoNetwork {
            get {
                return ResourceManager.GetString("OperationStatus_NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified folder is not found in FlashAir..
        /// </summary>
        public static string OperationStatus_NotFolderFound {
            get {
                return ResourceManager.GetString("OperationStatus_NotFolderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlashAir is changed..
        /// </summary>
        public static string OperationStatus_NotSameFlashAir {
            get {
                return ResourceManager.GetString("OperationStatus_NotSameFlashAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped..
        /// </summary>
        public static string OperationStatus_Stopped {
            get {
                return ResourceManager.GetString("OperationStatus_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timed out..
        /// </summary>
        public static string OperationStatus_TimedOut {
            get {
                return ResourceManager.GetString("OperationStatus_TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for auto check time..
        /// </summary>
        public static string OperationStatus_WaitingAutoCheck {
            get {
                return ResourceManager.GetString("OperationStatus_WaitingAutoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Check Interval.
        /// </summary>
        public static string Options_AutoCheckInterval {
            get {
                return ResourceManager.GetString("Options_AutoCheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Options_Browse {
            get {
                return ResourceManager.GetString("Options_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to choose to delete image in FlashAir on copy.
        /// </summary>
        public static string Options_ChooseDeleteOnCopy {
            get {
                return ResourceManager.GetString("Options_ChooseDeleteOnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Options_Connection {
            get {
                return ResourceManager.GetString("Options_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder for each date.
        /// </summary>
        public static string Options_CreateDatedFolder {
            get {
                return ResourceManager.GetString("Options_CreateDatedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Options_Date {
            get {
                return ResourceManager.GetString("Options_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Options_DateAll {
            get {
                return ResourceManager.GetString("Options_DateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from calendar.
        /// </summary>
        public static string Options_DateSelect {
            get {
                return ResourceManager.GetString("Options_DateSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Options_DateToday {
            get {
                return ResourceManager.GetString("Options_DateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete On Copy.
        /// </summary>
        public static string Options_DeleteOnCopy {
            get {
                return ResourceManager.GetString("Options_DeleteOnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make file extension lowercase.
        /// </summary>
        public static string Options_ExtensionLowercase {
            get {
                return ResourceManager.GetString("Options_ExtensionLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Options_File {
            get {
                return ResourceManager.GetString("Options_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle JPEG image only.
        /// </summary>
        public static string Options_HandleJpegOnly {
            get {
                return ResourceManager.GetString("Options_HandleJpegOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Options_Info {
            get {
                return ResourceManager.GetString("Options_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Copy.
        /// </summary>
        public static string Options_InstantCopy {
            get {
                return ResourceManager.GetString("Options_InstantCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Options_Language {
            get {
                return ResourceManager.GetString("Options_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Folder (Copy Destination).
        /// </summary>
        public static string Options_LocalFolder {
            get {
                return ResourceManager.GetString("Options_LocalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a folder to copy images..
        /// </summary>
        public static string Options_LocalFolderExplanation {
            get {
                return ResourceManager.GetString("Options_LocalFolderExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not select once copied image on check.
        /// </summary>
        public static string Options_OnceCopied {
            get {
                return ResourceManager.GetString("Options_OnceCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open by Explorer.
        /// </summary>
        public static string Options_OpenByExplorer {
            get {
                return ResourceManager.GetString("Options_OpenByExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order from newer image.
        /// </summary>
        public static string Options_OrderFromNewer {
            get {
                return ResourceManager.GetString("Options_OrderFromNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Options_Path {
            get {
                return ResourceManager.GetString("Options_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Recycle Bin if image in FlashAir is deleted.
        /// </summary>
        public static string Options_Recycle {
            get {
                return ResourceManager.GetString("Options_Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlashAir Address (Copy Source).
        /// </summary>
        public static string Options_RemoteAddress {
            get {
                return ResourceManager.GetString("Options_RemoteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only Read-only image on check.
        /// </summary>
        public static string Options_SelectReadOnly {
            get {
                return ResourceManager.GetString("Options_SelectReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout Duration.
        /// </summary>
        public static string Options_TimeoutDuration {
            get {
                return ResourceManager.GetString("Options_TimeoutDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://emoacht.github.io/SnowyImageCopy/index.html.
        /// </summary>
        public static string ProjectSite {
            get {
                return ResourceManager.GetString("ProjectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to readme_en.html#delete.
        /// </summary>
        public static string ReadmeFile {
            get {
                return ResourceManager.GetString("ReadmeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app will terminate, because unexpected problem happened. Leave exception log on Desktop?.
        /// </summary>
        public static string RecordException {
            get {
                return ResourceManager.GetString("RecordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from FlashAir completed..
        /// </summary>
        public static string ToastBody_CopyCompleted {
            get {
                return ResourceManager.GetString("ToastBody_CopyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} images, {1} seconds).
        /// </summary>
        public static string ToastBodyExtra_CopyCompleted {
            get {
                return ResourceManager.GetString("ToastBodyExtra_CopyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Completed.
        /// </summary>
        public static string ToastHeadline_CopyCompleted {
            get {
                return ResourceManager.GetString("ToastHeadline_CopyCompleted", resourceCulture);
            }
        }
    }
}
